name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # Ensure login is for GHCR, not Docker Hub
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG="ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/telegram-bot:${{ github.sha }}"
          docker build -t $IMAGE_TAG .

      - name: Push Docker image to GHCR
        run: |
          IMAGE_TAG="ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/telegram-bot:${{ github.sha }}"
          docker push $IMAGE_TAG

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi via SSH
        run: |
          IMAGE_TAG="ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/telegram-bot:${{ github.sha }}"
          sshpass -p "${{ secrets.RPI_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.RPI_USER }}@${{ secrets.RPI_IP }} << 'EOF'
            echo "Pulling latest image..."
            sudo docker pull $IMAGE_TAG
            
            echo "Stopping existing container..."
            sudo docker stop telegram-bot || true
            
            echo "Removing old container..."
            sudo docker rm telegram-bot || true
            
            echo "Running new container..."
            sudo docker run -d --restart unless-stopped --name telegram-bot $IMAGE_TAG
          EOF
