name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/telegram-bot:${{ github.sha }} .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/telegram-bot:${{ github.sha }}

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: SSH into Raspberry Pi and Deploy
        run: |
          sshpass -p "${{ secrets.RPI_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.RPI_USER }}@${{ secrets.RPI_IP }} << 'EOF'
            sudo docker pull ghcr.io/${{ github.repository_owner }}/telegram-bot:${{ github.sha }}
            sudo docker stop telegram-bot || true
            sudo docker rm telegram-bot || true
            sudo docker run -d --name telegram-bot ghcr.io/${{ github.repository_owner }}/telegram-bot:${{ github.sha }}
          EOF
      
