name: Deploy Telegram Bot

on:
  push:
    branches:
      - feat/permissions  # Trigger workflow only on master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/booking-bot:latest .

      - name: Push Image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/booking-bot:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        shell: bash

      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            docker stop telegram-bot || true
            docker rm telegram-bot || true
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/booking-bot:latest
            docker run -d --env-file /path/to/.env --name telegram-bot ghcr.io/${{ secrets.GHCR_USERNAME }}/booking-bot:latest
